### PR TITLE
Add Alpine support

### PR DESCRIPTION
**Pull request by PureTryOut**
Meaning: add Alpine support to setup.sh and install an OpenRC init file rather than systemd when required.

Note that for the service file to work https://github.com/MayaPosch/NymphCast/issues/5 is required as OpenRC doesn't support a working directory and can thus not find the apps directory.

### CODE REVIEW

**Comment by MayaPosch** [comment]
I'm finding that the poco-dev and ffmpeg-dev dependencies do not seem to be available on Alpine? I did perform an `apk update`, but nothing changed.

**Comment by PureTryOut** [comment]
[poco-dev is available in the testing repository](https://pkgs.alpinelinux.org/packages?name=poco-dev&branch=edge&arch=x86_64) (needs Alpine edge rather than latest stable) and [ffmpeg-dev in the community repository](https://pkgs.alpinelinux.org/packages?name=ffmpeg-dev&branch=edge&arch=x86_64). I'm guessing you only have the main repository enabled.

**Comment by MayaPosch** [comment]
Yes, I got the latest release from the Alpine website. What's the current schedule for ffmpeg and poco making it into the 'stable' repository?

**Comment by PureTryOut** [comment]
`ffmpeg` is already in the "stable" repository, you just need to enable the community repositories in `/etc/apk/repositories`.

For Poco, it depends. It currently doesn't have a maintainer but I'm going to pick that up. I'm going to try and get it in Alpine 3.12.

**Comment by PureTryOut** [comment]
This is now ready to merge.

**Pull request merged**
